<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>FS2Hercules</AssemblyName>
    <Description>Adds the GTF Hercules from FreeSpace 2</Description>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
    <Managed>$(GameDir)\NuclearOption_Data\Managed</Managed>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="$(Managed)\Assembly-CSharp.dll" Private="false" />
    <Reference Include="$(Managed)\Mirage.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.PhysicsModule.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.ImageConversionModule.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.ParticleSystemModule.dll" Private="false" />
    <Reference Include="$(Managed)\UnityEngine.AudioModule.dll" Private="false" />
    <Reference Include="$(GameDir)\BepInEx\core\BepInEx.dll" Private="false" />
    <Reference Include="$(GameDir)\BepInEx\core\0Harmony.dll" Private="false" />
  </ItemGroup>
</Project>
